# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node / Angular Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:    
    - name: Restore Project Packages     
      run: npm install
      
    - name: Build Angular Artifact     
      run: ng build
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
       name: archive.zip
       path: dist\PM_APP\browser
