# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node / Angular Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:   
    - uses: actions/checkout@v4
    
    - name: Restore Project Packages     
      run: npm install

    - name: Get typescript package     
      run: npm install -g typescript

    - name: Get Angular CLI     
      run: npm install -g @angular/cli
      
    - name: Build Angular Artifact     
      run: ng build
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
       name: archive.zip
       path: dist/PM_APP/browser
       
  deploy-dev:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:  
      name: dev
      url: https://github.com/Madondnh/Project-Management-Tool_Release
    steps:
    - name: Download candidate artifacts
      uses: actions/download-artifact@v4
      with:
        name: archive.zip

    - name: Display structure of downloaded files
      run: ls -R
    
    - name: Extract artifacts
      run: unzip '${{github.workspace}}/archive.zip' -d build_output
    - name: Push Build to Another Repository
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          # The folder where you unzipped the files
          folder: build_output     
          # The full name of the repo you are pushing to
          repository-name: Madondnh/Project-Management-Tool_Release
          
          # The branch in the destination repo (e.g., 'main' or 'gh-pages')
          branch: main 
          
          # Use a Personal Access Token (PAT) stored in your Secrets
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Set to true if you want to delete existing files in the 
          # destination repo that aren't in the current build
          clean: true
